name: Immkoala GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Check-Network:
    runs-on: ubuntu-latest
    steps:
      - name: Check network
        run: nc -zv 49.232.28.218 22
  Copy-Files-To-The-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy files to the server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 49.232.28.218 >> ~/.ssh/known_hosts
          scp -r ${{ github.workspace }}/* root@49.232.28.218:/root/immkoala